### ISSUE TITLE
Build failure on armv7 FreeBSD

### ISSUE THREAD

**Issue by clausecker** [astral-sh/tokio-tar#100]
This crate fails to build on armv7 FreeBSD 15.1:

```
error[E0277]: the trait bound `i32: From<u32>` is not satisfied
  --> /wrkdirs/usr/ports/devel/uv/work/uv-0.11.26/cargo-crates/astral-tokio-tar-0.6.3/src/entry.rs:67:47
   |
67 |     let nanoseconds = duration.subsec_nanos().into();
   |                                               ^^^^ the trait `From<u32>` is not implemented for `i32`
   |
   = help: `i32` implements trait `From<T>`:
             From<SignalKind>
             From<Simd<i16, 2>>
             From<Simd<i8, 4>>
             From<bool>
             From<errno::Errno>
             From<i16>
             From<i8>
             From<socket2::Domain>
           and 4 others
   = note: required for `u32` to implement `Into<i32>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `astral-tokio-tar` (lib) due to 1 previous error
```

Please check.  I will try to work around this using

    let nanoseconds = duration.subsec_nanos() as i32;

instead.
